## spring security 配置
security:
  oauth2:
    client:
      client-id: ENC(ltJPpR50wT0oIY9kfOe1Iw==)
      client-secret: ENC(ltJPpR50wT0oIY9kfOe1Iw==)
      scope: server
      # 默认放行url,子模块重写时application-dev.yml中的公共配置会被覆盖,所以要把公共配置中的放行url再写一次
      ignore-urls:
        - /actuator/**
        - /v2/api-docs
        - /user/info/*
        - /social/info/*
        - /mobile/*
        - /log/save

# 数据源
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1qaz2wsx
    url: jdbc:mysql://localhost:3306/pigxx?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true

## 文件系统
minio:
  url: http://127.0.0.1:9000
  access-key: 2M01I1SJN6YXYKK7PZUY
  secret-key: j5gE+N+Veqj6npP2sfrNn7222FZBwdpw72AuAntO
#  access-key: S3Y336QJ0ZYFF5S6L9XG
#  secret-key: EREmJrcmQnZuoWY7gSjFqflos069Uv6EQcgMdZhm

# Logger Config
logging:
  level:
    com.pig4cloud.pigx.admin.mapper: debug

# 租户表维护
pigx:
  tenant:
    column: tenant_id
    tables:
      - sys_user
      - sys_role
      - sys_dept
      - sys_log
      - sys_social_details
      - sys_dict
      - sys_log
