-- MySQL Script generated by MySQL Workbench
-- Tue Apr  9 13:45:40 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mdm
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mdm` ;

-- -----------------------------------------------------
-- Schema mdm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mdm` DEFAULT CHARACTER SET utf8 ;
USE `mdm` ;

-- -----------------------------------------------------
-- Table `mdm`.`m_model`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mdm`.`m_model` ;

CREATE TABLE `m_model` (
  `id` varchar(64) NOT NULL DEFAULT '',
  `name` varchar(64) DEFAULT '' COMMENT '模型名称',
  `description` varchar(512) DEFAULT NULL COMMENT '描述，说明',
  `createId` int(11) DEFAULT NULL,
  `updateId` int(11) DEFAULT NULL,
  `createTime` datetime DEFAULT NULL COMMENT '创建时间',
  `updateTime` datetime DEFAULT NULL COMMENT '更新时间',
  `logSave` char(1) DEFAULT NULL COMMENT '是否保存日志：0：否，1：是',
  `saveDays` int(11) DEFAULT NULL COMMENT '日志保留天数',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `mdm`.`m_entities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mdm`.`m_entities` ;

CREATE TABLE IF NOT EXISTS `mdm`.`m_entities` (
  `id` VARCHAR(64) NOT NULL,
  `name` VARCHAR(45) NULL COMMENT '实体名称',
  `desc` VARCHAR(512) NULL COMMENT '实体说明',
  `hasTempTable` CHAR(1) NULL COMMENT '是否有临时表',
  `tempTable` VARCHAR(45) NULL COMMENT '临时表名称',
  `codeAutomatic` CHAR(1) NULL COMMENT '是否自动创建代码值：0否，1是\n',
  `codeAutomaticStart` INT NULL COMMENT '添加实例时，选择自动生成代码，设定的起始值',
  `createId` INT(11) NULL COMMENT '创建者id',
  `createTime` DATETIME NULL COMMENT '创建时间',
  `updateId` INT(11) NULL COMMENT '更新者id',
  `updateTime` DATETIME NULL COMMENT '更新时间',
  `modelId` VARCHAR(64) NOT NULL COMMENT '所属模型id',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mdm`.`m_attribute`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mdm`.`m_attribute` ;

CREATE TABLE IF NOT EXISTS `mdm`.`m_attribute` (
  `id` VARCHAR(64) NOT NULL,
  `name` VARCHAR(250) NULL COMMENT '名称',
  `showName` VARCHAR(250) NULL COMMENT '显示名称',
  `desc` VARCHAR(512) NULL COMMENT '说明',
  `type` VARCHAR(45) NULL COMMENT '属性类型',
  `dataType` VARCHAR(45) NULL COMMENT '数据类型',
  `dataLimit` INT NULL COMMENT '数据限制',
  `entityId` VARCHAR(64) NULL COMMENT '所属实体id',
  `createId` INT(11) NULL COMMENT '创建者id',
  `createTime` DATETIME NULL COMMENT '创建时间',
  `updateId` INT(11) NULL COMMENT '更新者id',
  `updateTime` DATETIME NULL COMMENT '更新时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mdm`.`m_bRule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mdm`.`m_bRule` ;

CREATE TABLE IF NOT EXISTS `mdm`.`m_bRule` (
  `id` VARCHAR(64) NOT NULL,
  `name` VARCHAR(64) NULL COMMENT '规则名称',
  `desc` VARCHAR(45) NULL COMMENT '说明',
  `publish` CHAR(1) NULL COMMENT '是否发布',
  `createId` INT(11) NULL COMMENT '创建者',
  `createTime` DATETIME NULL COMMENT '创建时间',
  `updateId` INT(11) NULL,
  `updateTime` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mdm`.`m_entity_sync`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mdm`.`m_entity_sync` ;

CREATE TABLE IF NOT EXISTS `mdm`.`m_entity_sync` (
  `id` VARCHAR(64) NOT NULL,
  `sourceModelId` VARCHAR(64) NULL COMMENT '源模型id',
  `sourceEntityId` VARCHAR(64) NULL COMMENT '源实体id',
  `targetModelId` VARCHAR(64) NULL COMMENT '目标模型id',
  `targetEntityId` VARCHAR(64) NULL COMMENT '目标实体id',
  `name` VARCHAR(250) NULL COMMENT '名称',
  `syncStyle` CHAR(1) NULL COMMENT '同步方式：0自动同步（需设定频率）\n1手动同步（按需同步）',
  `syncInterval` INT NULL COMMENT '同步间隔',
  `intervalUnit` CHAR(1) NULL COMMENT '间隔单位（小时/天）0/1',
  `createId` INT(11) NULL COMMENT '创建者id',
  `updateId` INT(11) NULL COMMENT '更新者id',
  `createTime` DATETIME NULL COMMENT '创建时间',
  `updateTime` DATETIME NULL COMMENT '更新时间',
  `status` CHAR(1) NULL COMMENT '状态（0：未执行，1：执行中）',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mdm`.`m_index`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mdm`.`m_index` ;

CREATE TABLE IF NOT EXISTS `mdm`.`m_index` (
  `id` VARCHAR(64) NOT NULL,
  `name` VARCHAR(250) NULL COMMENT '名称',
  `isSingle` CHAR(1) NULL COMMENT '是否唯一（0：否，1：是）',
  `createId` INT(11) NULL COMMENT '创建者id',
  `createTime` DATETIME NULL COMMENT '创建时间',
  `updateId` INT(11) NULL COMMENT '更新者id',
  `updateTime` DATETIME NULL COMMENT '更新时间',
  `status` CHAR(1) NULL COMMENT '状态',
  `m_entities_id` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mdm`.`m_index_attr`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mdm`.`m_index_attr` ;

CREATE TABLE IF NOT EXISTS `mdm`.`m_index_attr` (
  `id` VARCHAR(64) NOT NULL,
  `indexId` VARCHAR(64) NULL COMMENT '索引的id',
  `attrId` VARCHAR(64) NULL COMMENT '属性id',
  `m_index_id` VARCHAR(64) DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mdm`.`m_rule_script`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mdm`.`m_rule_script` ;

CREATE TABLE IF NOT EXISTS `mdm`.`m_rule_script` (
  `id` VARCHAR(64) NOT NULL,
  `ruleId` VARCHAR(64) NULL COMMENT '规则id',
  `type` VARCHAR(64) NULL COMMENT 'if/then/else',
  `script` VARCHAR(250) NULL COMMENT '语句',
  `link` VARCHAR(3) NULL COMMENT '连接符号：and、or、not',
  `m_bRule_id` VARCHAR(64) NOT NULL,
  `publish` CHAR(1) NULL COMMENT '是否发布：0/未发布，1/发布',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mdm`.`m_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mdm`.`m_view` ;

CREATE TABLE IF NOT EXISTS `mdm`.`m_view` (
  `id` VARCHAR(64) NOT NULL,
  `name` VARCHAR(250) NULL COMMENT '视图名称',
  `modelId` VARCHAR(64) NULL COMMENT '模型id',
  `includeDelete` CHAR(1) NULL COMMENT '是否包含被删除成员',
  `entityId` VARCHAR(64) NULL COMMENT '实体id',
  `createId` INT(11) NULL COMMENT '创建者id',
  `creeateTime` DATETIME NULL COMMENT '创建时间',
  `updateId` INT(11) NULL COMMENT '更新者id',
  `updateTime` DATETIME NULL COMMENT '更新时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
